config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'

  get 'welcome/index'

  resources :users
  resources :sessions
  resources :messages

  root 'welcome#index'

  get 'outbox' => 'messages#outbox'
  get 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#new'
  get 'add_friend' => 'connections#add_friend'
  get 'unfriend' => 'connections#unfriend'

end

app/models/connection.rb
class Connection < ActiveRecord::Base
    belongs_to :from, class_name: "User", foreign_key: 'from_id'
    belongs_to :to, class_name: "User", foreign_key: 'to_id'
end

app/models/message.rb
class Message < ActiveRecord::Base
    belongs_to :sender, class_name: "User", foreign_key: "sender_id"
    belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :sent_messages, class_name: "Message", foreign_key: "sender_id"
    has_many :received_messages, class_name: "Message", foreign_key: "receiver_id"
    has_many :friends, class_name: "Connection", foreign_key: "from_id"

    has_secure_password

    validates :email, :name, :password, :password_confirmation, presence: true
    validates_confirmation_of :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?, :is_friend?

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def signed_in?
    current_user != nil
  end

  def is_friend?(user_id)
    current_user.friends.where(:to_id => user_id).any?
  end

  def check_login
    redirect_to login_path unless signed_in?
  end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController

  def add_friend
    @new_friend = Connection.new(:from_id => current_user.id, :to_id => User.find(connection_params[:to_id]).id)
    if @new_friend.save
      redirect_to users_path
    else
      'errors'
    end
  end

  def unfriend
    @friend = Connection.where(:to_id => connection_params[:to_id])
    if @friend.any? && @friend.destroy_all
      redirect_to users_path
    else
      'User cannot found'
    end
  end

  private
    def connection_params
      params.permit(:to_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :check_login

  def index
    @messages = current_user.received_messages.reverse_order
  end

  def outbox
    @messages = current_user.sent_messages.reverse_order
  end

  def show
    @message = Message.find(params[:id])
    if @message.receiver_id != session[:user_id]
      @message = nil
      flash[:error] = "You can only view messges sent to you."
    elsif @message.read
      @message = nil
      flash[:error] = "You already view the content of this message."
    else
      @message.read = true
      @message.save
    end
  end

  def new
    @friends = current_user.friends.collect{|f| f.to}
  end

  def create
      @message = Message.new(message_params)
      @message.sender = current_user
      @message.receiver = User.find(message_params[:receiver_id])

      if @message.save
        redirect_to messages_path
      else
        render 'new'
      end
  end

  private
  def message_params
    params.require(:message).permit(:body, :receiver_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(:email => params[:user][:email])

    if @user && @user.authenticate(params[:user][:password])
        redirect_to messages_path
        session[:user_id] = @user.id
    else
        @user ||= User.new
        @user.errors.add(:base, "Invalid username or password")
        render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :check_login, only: :index

    def index
        @users = User.all
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to messages_path
        else
            render 'welcome/index'
        end
    end

    private
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: 'alert-success', error: 'alert-danger', warning: 'alert-warning'}[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "text-center alert #{bootstrap_class_for(msg_type)} fade in") do
        concat content_tag(:button, 'x'.html_safe, class: 'close', data: {dismiss: 'alert'})
        concat message
      end)
      flash.clear
    end
    nil
  end
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Incognitochat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>



<body>

    <!-- Navigation -->
    <nav class="navbar navbar-light navbar-fixed-top bg-faded" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <a class="navbar-brand" href="<%= root_path %>">Coder Chat</a>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          &#9776;
        </button>
        <div class="collapse navbar-toggleable-xs" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="nav-item">
                    <%= active_link_to "My messages", messages_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= active_link_to "Sent messages", outbox_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= active_link_to "Add friends", users_path, class: "nav-link" %>
                </li>
                <% if signed_in? %>
                    <li class="nav-item">
                        <%= active_link_to "Log out", logout_path, class: 'nav-link' %>
                    </li>
                <% end %>
            </ul>
        </div>
      <!-- /.navbar-collapse -->
    </nav>
    <div class="navtop"></div>

    <!-- Page Content -->
    <%= yield %>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li class="nav-item">
                            <a class="nav-link" href="#about">About</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li class="nav-item">
                            <a class="nav-link" href="#services">Services</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li class="nav-item">
                            <a class="nav-link" href="#contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Your Company 2014. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

app/views/messages/_message.html.erb
<%= link_to message_path(message.id), class: "list-group-item #{'unread' unless message.read}" do %>
  <div class="list-group-item-heading"><b><%= message.sender.name %></b> <span class="message-time pull-right"><%= time_ago_in_words(message.created_at) %> ago</span></div>
  <p class="list-group-item-text"><%= truncate message.body, length: 45 %></p>
<% end %>

app/views/messages/index.html.erb
<div class="container space-buffer">
  <div class="btn-toolbar" role="toolbar">
    <div class="btn-group" role="group">
      <%= link_to "New message", new_message_path, class: "btn btn-secondary" %>
    </div>
  </div>
  <br/>

  <h4>Incoming messages</h4>

  <div class="list-group">
    <%= render @messages %>
  </div>

</div>

app/views/messages/new.html.erb
<div class="container space-buffer">
  <div class="row">
    <div class="col-xl-6">
        <h3>Send a message</h3>
        <%= form_for Message.new do |f| %>
          <div class="form-group">
            <%= f.select :receiver_id, options_for_select(@friends.collect{|p| [p.name, p.id]}, params[:receiver_id]) %>
            <%= f.text_area 'body', class: 'form-control', placeholder: 'message content', rows: "10"  %>
          </div>
          <%= f.submit 'Send message', class: 'btn btn-primary' %>
          <%= link_to "Back", :back %>
        <% end %>
    </div>
  </div>
</div>

app/views/messages/outbox.html.erb
<div class="container space-buffer">
  <div class="btn-toolbar" role="toolbar">
    <div class="btn-group" role="group">
      <%= link_to "New message", new_message_path, class: "btn btn-secondary" %>
    </div>
  </div>
  <br/>

  <h4>Outgoing messages</h4>

  <div class="list-group">
    <%= render @messages %>
  </div>

</div>

app/views/messages/show.html.erb
<div class="container space-buffer">
  <div class="row">
    <div class="col-xl-6">
        <h3>Message content</h3>
        <%= flash_messages %>
        <% if @message %>
          <div>From: <%= @message.sender.name %></div>
          <div>To: <%= @message.receiver.name %></div>
          <pre><%= @message.body %></pre>
        <% end %>
        <%= link_to "Back", :back %>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div class="col-xs-12 col-md-4">
  <div class="card card-<%= cycle('male', 'female') %>">
    <%= image_tag user.try(:image_url) %>
    <div class="card-block">
      <h4 class="card-title"><%= user.try(:name) %></h4>
      <p><%= user.try(:email) %></p>
      <% if is_friend?(user.id) %>
        <%= link_to 'Send message', new_message_path(:receiver_id => user.id), class: 'btn btn-primary btn-sm' %>
        <%= link_to 'Unfriend', unfriend_path(:to_id => user.id), class: 'btn btn-link btn-sm' %>
      <% else %>
        <%= link_to 'Add friend', add_friend_path(:to_id => user.id), class: 'btn btn-primary btn-sm' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container space-buffer">
  <h3>Users</h3>
  <% @users.in_groups_of(3) do |group| %>
    <div class="row">
      <%= render partial: 'user', collection: group.compact %>
    </div>
  <% end %>
  <%= link_to 'Back', :back %>
</div>

app/views/users/new.html.erb
<div class="banner">
    <div class="container">
        <div class="row">
            <div class="col-sm-10 col-md-8 col-lg-6 col-xl-5">
                <h3>Sign up for Coder Chat</h3>
                <p></p>
                <div class="signup-form">
                  <%= form_for @user || User.new do |f| %>
                    <div class="form-group">
                      <%= f.text_field 'email', class: 'form-control', placeholder: 'your e-mail' %>
                    </div>
                     <div class="form-group">
                      <%= f.text_field 'name', class: 'form-control', placeholder: 'name' %>
                    </div>
                    <div class="form-group">
                      <div class="half-width">
                        <%= f.password_field 'password', class: 'form-control', placeholder: 'password' %>
                      </div>
                      <div class="half-width">
                        <%= f.password_field 'password_confirmation', class: 'form-control', placeholder: 'confirmation' %>
                      </div>
                    </div>
                    <% if @user && @user.errors.any? %>
                      <div class="alert alert-danger" role="alert">
                        <ul>
                          <% @user.errors.full_messages.each do |err| %>
                            <li>
                              <strong><%= err %></strong>
                            </li>
                          <% end %>
                        </ul>
                      </div>
                    <% end %>
                    <div class="form-group">
                        <%= f.submit 'Sign up', class: 'btn btn-block btn-primary btn-lg' %>
                    </div>
                  <% end %>
                </div>
                <div class="additional-links">By signing up you agree to <a href="#">Terms of Use</a> and <a href="#">Privacy</a></div>
            </div>
        </div>
    </div>
</div>

app/views/welcome/index.html.erb
<a name="about"></a>
<div class="intro-header">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Coder Chat</h1>
                    <h3>A chat client for the coders</h3>
                    <hr class="intro-divider">
                    <ul class="list-inline intro-social-buttons">
                        <li>
                            <%= link_to login_path, class: 'btn btn-secondary btn-lg' do %>
                              <i class="fa fa-sign-in fa-fw"></i> <span class="network-name">Login</span>
                            <% end %>
                        </li>
                        <li>
                            <%= link_to new_user_path, class: 'btn btn-secondary btn-lg' do %>
                              <i class="fa fa-user-plus fa-fw"></i> <span class="network-name">Sign up</span>
                            <% end %>
                        </li>
                        <li>
                            <%= link_to '#', class: 'btn btn-secondary btn-lg' do %>
                              <i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span>
                            <% end %>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>